version: '3'
volumes: 
  postgres-data:
services:
  db:
    image: postgres
    volumes: 
      - postgres-data:/var/lib/postgresql/data
  auth0:
    environment:
      - AUTH0_CLIENT_ID=0FnJS2WjJPmE5t1QssW7ueVDRJtaL92K
      - AUTH0_CLIENT_SECRET=3GRJvT6NWEjTL4X646aW8tKK23zdsDb6N5yoFw6bkxiXRpoJr5Xmm_yfbyXEi_q-
      - AUTH0_DOMAIN=tugboat.auth0.com
      - AUTH0_CALLBACK_URL=http://localhost:3000/auth/auth0/callback
      - AUTH0_AUDIENCE=https://tugboat.auth0.com/api/v2/
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/auth0app
    ports:
      - "3000:3000"
    depends_on:
      - db
