version: '3'
volumes: 
  postgres-data:
services:
  db:
    image: postgres
    volumes: 
      - postgres-data:/var/lib/postgresql/data
  auth0:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/auth0app
    ports:
      - "3000:3000"
    depends_on:
      - db
